import Foundation

extension Word {
    static var list3Decks: [Word] {
        [
            Word(
                id: 3000,
                deckID: 3,
                japanese: "締切",
                english: "deadline",
                partOfSpeech: "n.",
                exampleEnglish: "When is the due date?",
                exampleJapanese: "締切はいつですか。",
            ),
            Word(
                id: 3001,
                deckID: 3,
                japanese: "先に",
                english: "ahead",
                partOfSpeech: "adv.",
                exampleEnglish: "Please go ahead with the meeting without me as I'm running late due to another meeting.",
                exampleJapanese: "他のミーティングがあって、ちょっと遅れるので、先に始めてください。",
            ),
            Word(
                id: 3002,
                deckID: 3,
                japanese: "事前に",
                english: "in advance",
                partOfSpeech: "adv.",
                exampleEnglish: "Please write the topics you want to talk about in advance.",
                exampleJapanese: "話したいトピックは、事前に書いておいてください。",
            ),
            Word(
                id: 3003,
                deckID: 3,
                japanese: "早めに",
                english: "early",
                partOfSpeech: "adv.",
                exampleEnglish: "I think we should work on this earlier because we will release it next week.",
                exampleJapanese: "これは来週リリースなので、早めにやった方がいいと思います。",
            ),
            Word(
                id: 3004,
                deckID: 3,
                japanese: "一旦",
                english: "temporarily",
                partOfSpeech: "adv.",
                exampleEnglish: "Let's move forward in this way, temporarily.",
                exampleJapanese: "一旦、このやり方で進めましょう。",
            ),
            Word(
                id: 3005,
                deckID: 3,
                japanese: "環境",
                english: "environment",
                partOfSpeech: "n.",
                exampleEnglish: "Everything has been reflected in the test environment.",
                exampleJapanese: "すべてテスト環境に反映しました。",
            ),
            Word(
                id: 3006,
                deckID: 3,
                japanese: "業務",
                english: "business",
                partOfSpeech: "n.",
                exampleEnglish: "The internet environment (ex: wifi) here is bad, which is hindering our business.",
                exampleJapanese: "ネット環境が悪くて、業務に支障が出ています。",
            ),
            Word(
                id: 3007,
                deckID: 3,
                japanese: "機能",
                english: "feature",
                partOfSpeech: "n.",
                exampleEnglish: "What features do you think would be more beneficial for our customers?",
                exampleJapanese: "どんな機能があったら、もっとお客様のためになると思う?",
            ),
            Word(
                id: 3008,
                deckID: 3,
                japanese: "運用",
                english: "operation",
                partOfSpeech: "n.",
                exampleEnglish: "That operation is not working properly.",
                exampleJapanese: "これは、ちゃんと運用ができていません。",
            ),
            Word(
                id: 3009,
                deckID: 3,
                japanese: "観点",
                english: "point of view",
                partOfSpeech: "n.",
                exampleEnglish: "From QA's point of view, the priority of this task is low.",
                exampleJapanese: "QAの観点からすると、このタスクの優先順位は低いです。",
            ),
            Word(
                id: 3010,
                deckID: 3,
                japanese: "重要",
                english: "important",
                partOfSpeech: "n./ na-adj.",
                exampleEnglish: "Which one is the most important issue?",
                exampleJapanese: "どれが一番重要な問題ですか。",
            ),
            Word(
                id: 3011,
                deckID: 3,
                japanese: "画面共有",
                english: "screen share",
                partOfSpeech: "n.",
                exampleEnglish: "Can you share your screen?",
                exampleJapanese: "画面共有してもらえる？",
            ),
            Word(
                id: 3012,
                deckID: 3,
                japanese: "デプロイ",
                english: "deployment",
                partOfSpeech: "n.",
                exampleEnglish: "I completed the deployment yesterday.",
                exampleJapanese: "昨日、デプロイ、完了しました。",
            ),
            Word(
                id: 3013,
                deckID: 3,
                japanese: "動作確認",
                english: "checking or testing operation",
                partOfSpeech: "n.",
                exampleEnglish: "When are you going to test the operation?",
                exampleJapanese: "動作確認はいつしますか。",
            ),
            Word(
                id: 3014,
                deckID: 3,
                japanese: "実装する",
                english: "implement",
                partOfSpeech: "v.",
                exampleEnglish: "We're going to implement this next week.",
                exampleJapanese: "これは来週実装します",
            ),
            Word(
                id: 3015,
                deckID: 3,
                japanese: "安定している",
                english: "be stable",
                partOfSpeech: "v.",
                exampleEnglish: "It's stable now since I've resolved the bugs.",
                exampleJapanese: "(それは、)バ グを直したので、今は安定しています。",
            ),
            Word(
                id: 3016,
                deckID: 3,
                japanese: "発生する",
                english: "occur",
                partOfSpeech: "v.",
                exampleEnglish: "An issue occurred when I was on call.",
                exampleJapanese: "オンコールのときに、問題が発生しました。",
            ),
            Word(
                id: 3017,
                deckID: 3,
                japanese: "対応する",
                english: "deal with",
                partOfSpeech: "v.",
                exampleEnglish: "For this issue, our team doesn't need to deal with it since another team will.",
                exampleJapanese: "これは、他のチームが対応してくれるので、うちのチームはしなくていいです。",
            ),
            Word(
                id: 3018,
                deckID: 3,
                japanese: "削除する",
                english: "delete",
                partOfSpeech: "v.",
                exampleEnglish: "I'll delete this because there are two tickets with the same content on Jira.",
                exampleJapanese: "Jiraに同じ内容のチケットが２つあるので、こっちは削除しますね。",
            ),
            Word(
                id: 3019,
                deckID: 3,
                japanese: "保存する",
                english: "save",
                partOfSpeech: "v.",
                exampleEnglish: "Sorry, I forgot to save it after I fixed it.",
                exampleJapanese: "すみません、修正したあと、保存し忘れました。",
            ),
            Word(
                id: 3020,
                deckID: 3,
                japanese: "検討する",
                english: "consider",
                partOfSpeech: "v.",
                exampleEnglish: "We're now considering how to roll it back.",
                exampleJapanese: "ロールバックのやり方は今検討中です。",
            ),
            Word(
                id: 3021,
                deckID: 3,
                japanese: "関係する",
                english: "be related to",
                partOfSpeech: "v.",
                exampleEnglish: "Who's the person related to this ticket?",
                exampleJapanese: "このチケットに関係してる人って、誰だっけ？",
            ),
            Word(
                id: 3022,
                deckID: 3,
                japanese: "継続する",
                english: "continue",
                partOfSpeech: "v.",
                exampleEnglish: "Let's continue the weekly sync meetings as we've been doing.",
                exampleJapanese: "weekly sync ミーティングは、今後も継続していきましょう。",
            ),
            Word(
                id: 3023,
                deckID: 3,
                japanese: "測る",
                english: "measure",
                partOfSpeech: "v.",
                exampleEnglish: "How do you measure if you've achieved your goal or not?",
                exampleJapanese: "この目標を達成したかどうかをどうやって測りますか。",
            ),
            Word(
                id: 3024,
                deckID: 3,
                japanese: "検索する",
                english: "search",
                partOfSpeech: "v.",
                exampleEnglish: "This screen layout makes it difficult to use the search function.",
                exampleJapanese: "この画面は検索しにくいですね。",
            ),
            Word(
                id: 3025,
                deckID: 3,
                japanese: "締切",
                english: "due date",
                partOfSpeech: "n.",
                exampleEnglish: "When is the due date?",
                exampleJapanese: "締切はいつですか。",
            ),
            Word(
                id: 3026,
                deckID: 3,
                japanese: "一旦",
                english: "for a moment",
                partOfSpeech: "adv.",
                exampleEnglish: "Let's move forward in this way, for a moment.",
                exampleJapanese: "一旦、このやり方で進めましょう。",
            ),
            Word(
                id: 3027,
                deckID: 3,
                japanese: "業務",
                english: "task",
                partOfSpeech: "n.",
                exampleEnglish: "The internet environment (ex: wifi) here is bad, which is hindering our tasks.",
                exampleJapanese: "ネット環境が悪くて、業務に支障が出ています。",
            ),
            Word(
                id: 3028,
                deckID: 3,
                japanese: "対応する",
                english: "handle",
                partOfSpeech: "v.",
                exampleEnglish: "For this issue, our team doesn't need to handle it since another team will.",
                exampleJapanese: "これは、他のチームが対応してくれるので、うちのチームはしなくていいです。",
            ),
            Word(
                id: 3029,
                deckID: 3,
                japanese: "検討する",
                english: "think about",
                partOfSpeech: "v.",
                exampleEnglish: "We're now thinking about how to roll it back.",
                exampleJapanese: "ロールバックのやり方は今検討中です。",
            ),
            Word(
                id: 3030,
                deckID: 3,
                japanese: "機能",
                english: "functions",
                partOfSpeech: "n.",
                exampleEnglish: "What functions do you think would be more beneficial for our customers?",
                exampleJapanese: "どんな機能があったら、もっとお客様のためになると思う?",
            ),
        ]
    }
}
