import Foundation

extension Word {
    static var list2Decks: [Word] {
        [
            Word(
                id: 2000,
                deckID: 2,
                japanese: "詳細",
                english: "details",
                partOfSpeech: "n.",
                exampleEnglish: "Please check the docs for details.",
                exampleJapanese: "詳細はdocsを見てください。",
            ),
            Word(
                id: 2001,
                deckID: 2,
                japanese: "詳しく",
                english: "in detail",
                partOfSpeech: "adv.",
                exampleEnglish: "Could you tell me about the incident in detail?",
                exampleJapanese: "どんなインシデントだったか詳しく教えてもらえますか。",
            ),
            Word(
                id: 2002,
                deckID: 2,
                japanese: "方針",
                english: "policy",
                partOfSpeech: "n.",
                exampleEnglish: "The company policy has not been decided yet.",
                exampleJapanese: "まだ会社の方針が決まってない。",
            ),
            Word(
                id: 2003,
                deckID: 2,
                japanese: "補足",
                english: "supplementary",
                partOfSpeech: "n.",
                exampleEnglish: "Let me add something to what Ken said,",
                exampleJapanese: "ケンさんの話への補足なんですけど、、、",
            ),
            Word(
                id: 2004,
                deckID: 2,
                japanese: "効果的",
                english: "effective",
                partOfSpeech: "adj.",
                exampleEnglish: "I think this way is effective.",
                exampleJapanese: "このやり方が効果的だと思います。",
            ),
            Word(
                id: 2005,
                deckID: 2,
                japanese: "達成する",
                english: "achieve",
                partOfSpeech: "v.",
                exampleEnglish: "We achieved our OKR last week.",
                exampleJapanese: "先週、OKRを達成しました。",
            ),
            Word(
                id: 2006,
                deckID: 2,
                japanese: "報告する",
                english: "report",
                partOfSpeech: "v.",
                exampleEnglish: "I will report on the project.",
                exampleJapanese: "プロジェクトについて報告します。",
            ),
            Word(
                id: 2007,
                deckID: 2,
                japanese: "議論する",
                english: "discuss",
                partOfSpeech: "v.",
                exampleEnglish: "EMs are discussing it now.",
                exampleJapanese: "それはEMが議論しているところです。",
            ),
            Word(
                id: 2008,
                deckID: 2,
                japanese: "不具合",
                english: "defect",
                partOfSpeech: "n.",
                exampleEnglish: "There are some defects, so I'll fix it by the end of the day.",
                exampleJapanese: "ちょっと不具合があるので、今日中に直します。",
            ),
            Word(
                id: 2009,
                deckID: 2,
                japanese: "順調に進む",
                english: "go smoothly",
                partOfSpeech: "",
                exampleEnglish: "The deployment went smoothly.",
                exampleJapanese: "デプロイはスムーズに完了しました。",
            ),
            Word(
                id: 2010,
                deckID: 2,
                japanese: "量",
                english: "amount",
                partOfSpeech: "n.",
                exampleEnglish: "There are too many tasks.",
                exampleJapanese: "タスクの量が多すぎます。",
            ),
            Word(
                id: 2011,
                deckID: 2,
                japanese: "具体的",
                english: "concrete",
                partOfSpeech: "adj.",
                exampleEnglish: "Could you expain the incident more concretely?",
                exampleJapanese: "具体的にどんなインシデントでしたか。",
            ),
            Word(
                id: 2012,
                deckID: 2,
                japanese: "状況",
                english: "situation",
                partOfSpeech: "n.",
                exampleEnglish: "We're in a tough situation in terms of QA resources.",
                exampleJapanese: "QAのリソースが厳しい状況です。",
            ),
            Word(
                id: 2013,
                deckID: 2,
                japanese: "現状",
                english: "present situation",
                partOfSpeech: "n.",
                exampleEnglish: "I'll explain about the present situation.",
                exampleJapanese: "現状を説明します。",
            ),
            Word(
                id: 2014,
                deckID: 2,
                japanese: "進捗確認",
                english: "progress check",
                partOfSpeech: "n.",
                exampleEnglish: "Let's start with a progress check.",
                exampleJapanese: "まずは、進捗確認をしましょう。",
            ),
            Word(
                id: 2015,
                deckID: 2,
                japanese: "優先順位",
                english: "priority",
                partOfSpeech: "n.",
                exampleEnglish: "I think we should decide the priority.",
                exampleJapanese: "優先順位を決めたほうがいいと思います。",
            ),
            Word(
                id: 2016,
                deckID: 2,
                japanese: "残る",
                english: "remain",
                partOfSpeech: "v.",
                exampleEnglish: "Are there any tickets left?",
                exampleJapanese: "残っているチケットはありますか。",
            ),
            Word(
                id: 2017,
                deckID: 2,
                japanese: "着手する",
                english: "initiate",
                partOfSpeech: "v.",
                exampleEnglish: "Have you already initiated it?",
                exampleJapanese: "それって、もう着手してますか？",
            ),
            Word(
                id: 2018,
                deckID: 2,
                japanese: "調整する",
                english: "adjust",
                partOfSpeech: "v.",
                exampleEnglish: "I'm thinking I should adjust my workload because I've been too busy these days.",
                exampleJapanese: "最近忙しすぎるので、タスクの量を調整したほうがいいいと思っています。",
            ),
            Word(
                id: 2019,
                deckID: 2,
                japanese: "認識",
                english: "recognition",
                partOfSpeech: "n.",
                exampleEnglish: "I'd like to make sure everyone's on the same page.",
                exampleJapanese: "全員で認識を合わせたいです。",
            ),
            Word(
                id: 2020,
                deckID: 2,
                japanese: "ずれる",
                english: "be out of alignment",
                partOfSpeech: "v.",
                exampleEnglish: "I'd like to make sure there's no misunderstanding between us.",
                exampleJapanese: "認識がずれてないか確認したいです。",
            ),
            Word(
                id: 2021,
                deckID: 2,
                japanese: "変更する",
                english: "change",
                partOfSpeech: "v.",
                exampleEnglish: "The schedule has been changed.",
                exampleJapanese: "スケジュールが変更しています。",
            ),
            Word(
                id: 2022,
                deckID: 2,
                japanese: "開始する",
                english: "start",
                partOfSpeech: "v.",
                exampleEnglish: "We will start a campaign next week.",
                exampleJapanese: "来週からキャンペーンが開始します。",
            ),
            Word(
                id: 2023,
                deckID: 2,
                japanese: "前倒しする",
                english: "reschedule to an earlier time",
                partOfSpeech: "v.",
                exampleEnglish: "Let's move up this project. (Ex: from next qtr to this qtr)",
                exampleJapanese: "このプロジェクトは、前倒しで進めましょう",
            ),
            Word(
                id: 2024,
                deckID: 2,
                japanese: "以降",
                english: "sometime after",
                partOfSpeech: "n.",
                exampleEnglish: "We're planning to do a code review sometime after next week.",
                exampleJapanese: "コードレビューは、来週以降の予定です",
            ),
            Word(
                id: 2025,
                deckID: 2,
                japanese: "補足",
                english: "additional",
                partOfSpeech: "n.",
                exampleEnglish: "Let me add something to what Ken said,",
                exampleJapanese: "ケンさんの話への補足なんですけど、、、",
            ),
            Word(
                id: 2026,
                deckID: 2,
                japanese: "不具合",
                english: "bug",
                partOfSpeech: "n.",
                exampleEnglish: "There are some bugs, so I'll fix it by the end of the day.",
                exampleJapanese: "ちょっと不具合があるので、今日中に直します。",
            ),
            Word(
                id: 2027,
                deckID: 2,
                japanese: "認識",
                english: "understanding",
                partOfSpeech: "n.",
                exampleEnglish: "I'd like to make sure everyone's on the same page.",
                exampleJapanese: "全員で認識を合わせたいです。",
            ),
            Word(
                id: 2028,
                deckID: 2,
                japanese: "認識",
                english: "work well.",
                partOfSpeech: "",
                exampleEnglish: "This is working well.",
                exampleJapanese: "これは、順調に進んでいます。",
            ),
            Word(
                id: 2029,
                deckID: 2,
                japanese: "(システムなどが)順調に動く",
                english: "run smoothly",
                partOfSpeech: "",
                exampleEnglish: "The app runs smoothly on Android.",
                exampleJapanese: "Androidは順調に動いています。",
            ),
        ]
    }
}
