import Foundation

extension Word {
    static var list5Decks: [Word] {
        [
            Word(
                id: 5000,
                deckID: 5,
                japanese: "雑談",
                english: "small talk",
                partOfSpeech: "n.",
                exampleEnglish: "We still have about 10 minutes left, shall we just small talk?",
                exampleJapanese: "まだ10分ぐらいあるので、ちょっと雑談でもしましょうか。",
            ),
            Word(
                id: 5001,
                deckID: 5,
                japanese: "段階",
                english: "phase",
                partOfSpeech: "n.",
                exampleEnglish: "I'm in the preparation phase of the test now.",
                exampleJapanese: "今は、テストの準備をしている段階です。",
            ),
            Word(
                id: 5002,
                deckID: 5,
                japanese: "既存",
                english: "existing",
                partOfSpeech: "n.",
                exampleEnglish: "I'll check the existing sources and then think about it.",
                exampleJapanese: "既存のソースを見て、考えてみます。",
            ),
            Word(
                id: 5003,
                deckID: 5,
                japanese: "事例",
                english: "case",
                partOfSpeech: "n.",
                exampleEnglish: "There was a similar case last week.",
                exampleJapanese: "先週、それに似た事例がありました。",
            ),
            Word(
                id: 5004,
                deckID: 5,
                japanese: "品質",
                english: "quality",
                partOfSpeech: "n.",
                exampleEnglish: "I think it'll be difficult to maintain the QA quality if we move the release date up.",
                exampleJapanese: "リリースを早めると、QAの品質を保つのは難しくなると思います。",
            ),
            Word(
                id: 5005,
                deckID: 5,
                japanese: "処理",
                english: "processing",
                partOfSpeech: "n.",
                exampleEnglish: "When do you think we'll finish processing the refund?",
                exampleJapanese: "返金処理は、いつ完了しそうですか。",
            ),
            Word(
                id: 5006,
                deckID: 5,
                japanese: "障害",
                english: "fault",
                partOfSpeech: "n.",
                exampleEnglish: "A lot of faults have been happening these days.",
                exampleJapanese: "最近、障害が多く発生している。",
            ),
            Word(
                id: 5007,
                deckID: 5,
                japanese: "クリティカル",
                english: "critical",
                partOfSpeech: "n-adj.",
                exampleEnglish: "There are no critical failures yet.",
                exampleJapanese: "今のところ、クリティカルな障害は起きてません。",
            ),
            Word(
                id: 5008,
                deckID: 5,
                japanese: "挙動",
                english: "(system) behavior",
                partOfSpeech: "n.",
                exampleEnglish: "Wait a second, the system behavior of Chrome is acting strange.",
                exampleJapanese: "ちょっと待って、Chromeの挙動がおかしい。",
            ),
            Word(
                id: 5009,
                deckID: 5,
                japanese: "やつ",
                english: "thing",
                partOfSpeech: "n. ※casual",
                exampleEnglish: "Is there something you plan to do QA for next week?",
                exampleJapanese: "来週QAする予定のやつ、ある？",
            ),
            Word(
                id: 5010,
                deckID: 5,
                japanese: "作成する",
                english: "make (document or plan)",
                partOfSpeech: "v.",
                exampleEnglish: "I've made a schedule for the next release, so please check it by the end of today if you haven't.",
                exampleJapanese: "リリースまでのスケジュールを作成したので、まだ見てない人は、今日中に確認してください",
            ),
            Word(
                id: 5011,
                deckID: 5,
                japanese: "設計する",
                english: "plan",
                partOfSpeech: "v.",
                exampleEnglish: "Please check here for the important points about planning AB tests.",
                exampleJapanese: "ABテストを設計するときの注意点については、ここを読んどいてください。",
            ),
            Word(
                id: 5012,
                deckID: 5,
                japanese: "拡張する",
                english: "expand",
                partOfSpeech: "v.",
                exampleEnglish: "Our infrastructure needs to be expanded as traffic grows.",
                exampleJapanese: "トラフィックの増加に伴い、インフラを拡張する必要があります。",
            ),
            Word(
                id: 5013,
                deckID: 5,
                japanese: "(内容を)詰める",
                english: "decide details",
                partOfSpeech: "v.",
                exampleEnglish: "We should think about this more in order to decide the details.",
                exampleJapanese: "この件、もう少し詰めた方がいいですね。",
            ),
            Word(
                id: 5014,
                deckID: 5,
                japanese: "任せる",
                english: "delegate",
                partOfSpeech: "v.",
                exampleEnglish: "I've delegated this project to Sato-san.",
                exampleJapanese: "このプロジェクトは、佐藤さんに任せました",
            ),
            Word(
                id: 5015,
                deckID: 5,
                japanese: "見積もる",
                english: "estimate",
                partOfSpeech: "v.",
                exampleEnglish: "I estimate it will take about 2 months in total",
                exampleJapanese: "見積もると、だいたいトータルで2ヶ月かかります。",
            ),
            Word(
                id: 5016,
                deckID: 5,
                japanese: "紐づく",
                english: "link",
                partOfSpeech: "v.",
                exampleEnglish: "This information is linked to customer ID.",
                exampleJapanese: "この情報は、お客様IDに紐づいています",
            ),
            Word(
                id: 5017,
                deckID: 5,
                japanese: "感じ",
                english: "like [something]",
                partOfSpeech: "n.",
                exampleEnglish: "It's like this.",
                exampleJapanese: "こんな感じです。",
            ),
            Word(
                id: 5018,
                deckID: 5,
                japanese: "以外",
                english: "besides",
                partOfSpeech: "n.",
                exampleEnglish: "Is there anything else you want to talk about besides the topics written here?",
                exampleJapanese: "ここに書いてあるトピック以外に何か話したいことありますか。",
            ),
            Word(
                id: 5019,
                deckID: 5,
                japanese: "同時に",
                english: "at the same time",
                partOfSpeech: "adv.",
                exampleEnglish: "There's a limit to the number of projects we can handle at the same time.",
                exampleJapanese: "同時に担当できるプロジェクトの数には限界があります",
            ),
            Word(
                id: 5020,
                deckID: 5,
                japanese: "結局",
                english: "after all",
                partOfSpeech: "adv.",
                exampleEnglish: "If we don't solve this problem, after all it'll happen just before the release.",
                exampleJapanese: "これを解決しておかないと、結局、リリース直前に問題が出てくる。",
            ),
            Word(
                id: 5021,
                deckID: 5,
                japanese: "ほぼ",
                english: "mostly",
                partOfSpeech: "adv.",
                exampleEnglish: "I've mostly finished this ticket.",
                exampleJapanese: "このチケットはほぼ終わりました",
            ),
            Word(
                id: 5022,
                deckID: 5,
                japanese: "そもそも",
                english: "in the first place",
                partOfSpeech: "adv.",
                exampleEnglish: "What was the point of this meeting in the first place?",
                exampleJapanese: "そもそも、このミーティングの目的はなんでしたっけ？",
            ),
            Word(
                id: 5023,
                deckID: 5,
                japanese: "どんどん",
                english: "one after the other (usually quickly)",
                partOfSpeech: "adv.",
                exampleEnglish: "Let's all share our opinions one after the other.",
                exampleJapanese: "どんどん意見を言ってくださいね",
            ),
            Word(
                id: 5024,
                deckID: 5,
                japanese: "〜側",
                english: "side",
                partOfSpeech: "n.",
                exampleEnglish: "OK, the QA side will deal with this.",
                exampleJapanese: "これはQA側で対応します",
            ),
            Word(
                id: 5025,
                deckID: 5,
                japanese: "雑談",
                english: "chat",
                partOfSpeech: "n.",
                exampleEnglish: "We still have about 10 minutes left, shall we just chat?",
                exampleJapanese: "まだ10分ぐらいあるので、ちょっと雑談でもしましょうか。",
            ),
            Word(
                id: 5026,
                deckID: 5,
                japanese: "障害",
                english: "system error",
                partOfSpeech: "n.",
                exampleEnglish: "A lot of system errors have been happening these days.",
                exampleJapanese: "最近、障害が多く発生している。",
            ),
            Word(
                id: 5027,
                deckID: 5,
                japanese: "クリティカル",
                english: "specially important",
                partOfSpeech: "n-adj.",
                exampleEnglish: "There are no specially important failures yet.",
                exampleJapanese: "今のところ、クリティカルな障害は起きてません。",
            ),
            Word(
                id: 5028,
                deckID: 5,
                japanese: "挙動",
                english: "acting",
                partOfSpeech: "n.",
                exampleEnglish: "Hold on, Chrome is acting weird.",
                exampleJapanese: "ちょっと待って、Chromeの挙動がおかしい。",
            ),
            Word(
                id: 5029,
                deckID: 5,
                japanese: "設計する",
                english: "design",
                partOfSpeech: "v.",
                exampleEnglish: "Please check here for the important points about designing AB tests.",
                exampleJapanese: "ABテストを設計するときの注意点については、ここを読んどいてください。",
            ),
            Word(
                id: 5030,
                deckID: 5,
                japanese: "任せる",
                english: "leave (something) with (someone)",
                partOfSpeech: "v.",
                exampleEnglish: "I've left this project with Sato-san.",
                exampleJapanese: "このプロジェクトは、佐藤さんに任せました",
            ),
            Word(
                id: 5031,
                deckID: 5,
                japanese: "以外",
                english: "except",
                partOfSpeech: "n.",
                exampleEnglish: "Is there anything else you want to talk about except the topics written here?",
                exampleJapanese: "ここに書いてあるトピック以外に何か話したいことありますか。",
            ),
            Word(
                id: 5032,
                deckID: 5,
                japanese: "同時に",
                english: "simultaneously",
                partOfSpeech: "adv.",
                exampleEnglish: "There's a limit to the number of projects we can handle simultaneously.",
                exampleJapanese: "同時に担当できるプロジェクトの数には限界があります",
            ),
            Word(
                id: 5033,
                deckID: 5,
                japanese: "結局",
                english: "in the end",
                partOfSpeech: "adv.",
                exampleEnglish: "If we don't solve this problem, in the end it'll happen just before the release.",
                exampleJapanese: "これを解決しておかないと、結局、リリース直前に問題が出てくる。",
            ),
            Word(
                id: 5034,
                deckID: 5,
                japanese: "設計する",
                english: "layout",
                partOfSpeech: "v.",
                exampleEnglish: "Please check here for the important points about layouting AB tests.",
                exampleJapanese: "ABテストを設計するときの注意点については、ここを読んどいてください。",
            ),
            Word(
                id: 5035,
                deckID: 5,
                japanese: "〜に展開されている",
                english: "be open to\n(someone or something)",
                partOfSpeech: "v.",
                exampleEnglish: "This document is now open to everyone.",
                exampleJapanese: "この資料は、全メンバーに展開されています",
            ),
        ]
    }
}
