import Foundation

extension Word {
    static var list4Decks: [Word] {
        [
            Word(
                id: 4000,
                deckID: 4,
                japanese: "時期",
                english: "period",
                partOfSpeech: "n.",
                exampleEnglish: "The release period is being adjusted.",
                exampleJapanese: "リリースの時期は、調整中です。",
            ),
            Word(
                id: 4001,
                deckID: 4,
                japanese: "未確定",
                english: "undecided",
                partOfSpeech: "n. / na-adj. ",
                exampleEnglish: "The schedule hasn't been decided yet.",
                exampleJapanese: "スケジュールは未確定です。",
            ),
            Word(
                id: 4002,
                deckID: 4,
                japanese: "不足",
                english: "shortage",
                partOfSpeech: "n.",
                exampleEnglish: "The shortage of communication among team members is becoming a problem.",
                exampleJapanese: "チーム内のコミュニケーション不足が、問題になっています。",
            ),
            Word(
                id: 4003,
                deckID: 4,
                japanese: "余裕",
                english: "time / money / space (to spare)",
                partOfSpeech: "n.",
                exampleEnglish: "We don't have time to spare since we have a lot of releases this month.",
                exampleJapanese: "今月は、リリースが多くて、みんな余裕があんまりない。",
            ),
            Word(
                id: 4004,
                deckID: 4,
                japanese: "正常",
                english: "normally, normal",
                partOfSpeech: "n. / na-adj.  ",
                exampleEnglish: "Since the system isn't working normally, Suzuki-san is going to check on it today.",
                exampleJapanese: "システムが正常に動いてないので、今日中に鈴木さんが確認する予定になっています。",
            ),
            Word(
                id: 4005,
                deckID: 4,
                japanese: "最優先",
                english: "top priority",
                partOfSpeech: "n.",
                exampleEnglish: "I think it's better to make this the top priority because the release is next week.",
                exampleJapanese: "これはリリースが来週なので、最優先で進めたほうがいいと思います。",
            ),
            Word(
                id: 4006,
                deckID: 4,
                japanese: "直接",
                english: "directly",
                partOfSpeech: "adv.",
                exampleEnglish: "Please talk to your manager directly if you have any problems.",
                exampleJapanese: "困ったことがあったら、直接マネージャーに相談してください。",
            ),
            Word(
                id: 4007,
                deckID: 4,
                japanese: "途中",
                english: "in the middle of",
                partOfSpeech: "n.",
                exampleEnglish: "Are you in the middle of working on this ticket?",
                exampleJapanese: "今、このチケットをやってる途中ですか。",
            ),
            Word(
                id: 4008,
                deckID: 4,
                japanese: "処理",
                english: "process",
                partOfSpeech: "n.",
                exampleEnglish: "I completed the refund process yesterday.",
                exampleJapanese: "返金処理は、昨日、完了しました。",
            ),
            Word(
                id: 4009,
                deckID: 4,
                japanese: "集中する",
                english: "concentrate on",
                partOfSpeech: "v.",
                exampleEnglish: "This week, our team will concentrate on improving the app’s stability.",
                exampleJapanese: "今週、チームはアプリの安定性向上に注力します。",
            ),
            Word(
                id: 4010,
                deckID: 4,
                japanese: "遅延する",
                english: "delay",
                partOfSpeech: "v.",
                exampleEnglish: "A system delay happened last night.",
                exampleJapanese: "昨日の夜、システムに遅延が発生しました。",
            ),
            Word(
                id: 4011,
                deckID: 4,
                japanese: "作業をする",
                english: "work",
                partOfSpeech: "v.",
                exampleEnglish: "I'll work on updating this tomorrow.",
                exampleJapanese: "明日、バージョンアップする作業をします。",
            ),
            Word(
                id: 4012,
                deckID: 4,
                japanese: "担当する",
                english: "be responsible for",
                partOfSpeech: "v.",
                exampleEnglish: "Do you know which team is responsible for this work?",
                exampleJapanese: "この業務は、どこのチームが担当してるか知ってる？",
            ),
            Word(
                id: 4013,
                deckID: 4,
                japanese: "追加する",
                english: "add",
                partOfSpeech: "v.",
                exampleEnglish: "Please add the topics you want to talk about to the notes.",
                exampleJapanese: "話したいトピックがある人は、議事録に追加しておいてくださいね。",
            ),
            Word(
                id: 4014,
                deckID: 4,
                japanese: "提案する",
                english: "propose",
                partOfSpeech: "v.",
                exampleEnglish: "If you want to propose anything, please DM me by tomorrow.",
                exampleJapanese: "何か提案がある人は、明日までに私にDMしてください。",
            ),
            Word(
                id: 4015,
                deckID: 4,
                japanese: "導入する",
                english: "implement",
                partOfSpeech: "v.",
                exampleEnglish: "The timing of implementing the new service hasn't been decided yet.",
                exampleJapanese: "新しいサービスを導入する時期はまだ決まってません。",
            ),
            Word(
                id: 4016,
                deckID: 4,
                japanese: "落ちる",
                english: "drop",
                partOfSpeech: "v.",
                exampleEnglish: "The service dropped temporarily late last night because of a spike in access.",
                exampleJapanese: "夜中にアクセスが集中して、サービスが一時的に落ちました。",
            ),
            Word(
                id: 4017,
                deckID: 4,
                japanese: "移動する",
                english: "move",
                partOfSpeech: "v.",
                exampleEnglish: "Tickets that we won't deal with this Q will be moved to the next sprint.",
                exampleJapanese: "今Q対応しないチケットは、次のSprintに移動しておきます。",
            ),
            Word(
                id: 4018,
                deckID: 4,
                japanese: "被る",
                english: "have a schedule conflict",
                partOfSpeech: "v. (*casual)",
                exampleEnglish: "Sorry, I can't join tomorrow's stand up because of a schedule conflict.",
                exampleJapanese: "すみません、他のミーティングと被ってるので、明日のスタンドアップミーティングに参加できません。",
            ),
            Word(
                id: 4019,
                deckID: 4,
                japanese: "ミーティングを抜ける",
                english: "leave the meeting",
                partOfSpeech: "v.",
                exampleEnglish: "[Situation: In a meeting]Sorry, I need to leave now because I have another meeting.",
                exampleJapanese: "【状況：ミーティングに出席中】すみません、次のミーティングがあるので、先に抜けますね。",
            ),
            Word(
                id: 4020,
                deckID: 4,
                japanese: "けっこう",
                english: "quite",
                partOfSpeech: "adv.",
                exampleEnglish: "Please take it easy now since we're going to be quite busy next month.",
                exampleJapanese: "来月はけっこう忙しくなると思うので、みなさん、今のうちにゆっくり休んでくださいね。",
            ),
            Word(
                id: 4021,
                deckID: 4,
                japanese: "ギリギリ",
                english: "at the last moment",
                partOfSpeech: "adv.",
                exampleEnglish: "It'll be really tight, but I think I'll just at the last moment get the ticket done by the deadline.",
                exampleJapanese: "このチケットは、ギリギリになりそうですが、締切までに終わると思います。",
            ),
            Word(
                id: 4022,
                deckID: 4,
                japanese: "基本的に",
                english: "basically",
                partOfSpeech: "adv.",
                exampleEnglish: "Basically, everyone's assignments won't change much from this Q to next Q.",
                exampleJapanese: "基本的に、来Qのみなさんのアサインは、今Qと変更ありません。",
            ),
            Word(
                id: 4023,
                deckID: 4,
                japanese: "ちなみに",
                english: "also",
                partOfSpeech: "adv.",
                exampleEnglish: "Also, do you know when the release period will be decided? Approximately?",
                exampleJapanese: "ちなみに、いつぐらいまでにリリースの時期が決まるか、わかりますか。",
            ),
            Word(
                id: 4024,
                deckID: 4,
                japanese: "視点",
                english: "point of view",
                partOfSpeech: "n.",
                exampleEnglish: "Think about it from the customer's point of view.",
                exampleJapanese: "お客様視点で考えてみて。",
            ),
            Word(
                id: 4025,
                deckID: 4,
                japanese: "時期",
                english: "season",
                partOfSpeech: "n.",
                exampleEnglish: "The release season is being adjusted.",
                exampleJapanese: "リリースの時期は、調整中です。",
            ),
            Word(
                id: 4026,
                deckID: 4,
                japanese: "不足",
                english: "lack of",
                partOfSpeech: "n.",
                exampleEnglish: "The lack of communication among team members is becoming a problem.",
                exampleJapanese: "チーム内のコミュニケーション不足が、問題になっています。",
            ),
            Word(
                id: 4027,
                deckID: 4,
                japanese: "余裕",
                english: "have room in someone's mind",
                partOfSpeech: "n.",
                exampleEnglish: "We don't have time to spare since we have a lot of releases this month.",
                exampleJapanese: "今月は、リリースが多くて、みんな余裕があんまりない。",
            ),
            Word(
                id: 4028,
                deckID: 4,
                japanese: "途中",
                english: "halfway",
                partOfSpeech: "n.",
                exampleEnglish: "Are you in the halfway of working on this ticket?",
                exampleJapanese: "今、このチケットをやってる途中ですか。",
            ),
            Word(
                id: 4029,
                deckID: 4,
                japanese: "集中する",
                english: "focus on",
                partOfSpeech: "v.",
                exampleEnglish: "We need to focus on solving the core issue.",
                exampleJapanese: "私たちは核心的な問題の解決に集中する必要があります。",
            ),
            Word(
                id: 4030,
                deckID: 4,
                japanese: "集中した 濃縮された",
                english: "concentrated",
                partOfSpeech: "",
                exampleEnglish: "What time is access to the site most concentrated?",
                exampleJapanese: "サイトへのアクセスは、どの時間帯が一番集中しますか。",
            ),
            Word(
                id: 4031,
                deckID: 4,
                japanese: "担当する",
                english: "be in charge of",
                partOfSpeech: "v.",
                exampleEnglish: "Do you know which team is in charge of this work?",
                exampleJapanese: "この業務は、どこのチームが担当してるか知ってる？",
            ),
            Word(
                id: 4032,
                deckID: 4,
                japanese: "提案する",
                english: "suggest",
                partOfSpeech: "v.",
                exampleEnglish: "If you want to suggest anything, please DM me by tomorrow.",
                exampleJapanese: "何か提案がある人は、明日までに私にDMしてください。",
            ),
            Word(
                id: 4033,
                deckID: 4,
                japanese: "落ちる",
                english: "go down",
                partOfSpeech: "v.",
                exampleEnglish: "The service went down temporarily late last night because of a spike in access.",
                exampleJapanese: "夜中にアクセスが集中して、サービスが一時的に落ちました。",
            ),
            Word(
                id: 4034,
                deckID: 4,
                japanese: "移動する",
                english: "shift",
                partOfSpeech: "v.",
                exampleEnglish: "Tickets that we won't deal with this Q will be shifted to the next sprint.",
                exampleJapanese: "今Q対応しないチケットは、次のSprintに移動しておきます。",
            ),
            Word(
                id: 4035,
                deckID: 4,
                japanese: "ギリギリ",
                english: "barely",
                partOfSpeech: "adv.",
                exampleEnglish: "It'll be really tight, but I think I'll just barely get the ticket done by the deadline.",
                exampleJapanese: "このチケットは、ギリギリになりそうですが、締切までに終わると思います。",
            ),
            Word(
                id: 4036,
                deckID: 4,
                japanese: "ちなみに",
                english: "in addition",
                partOfSpeech: "adv.",
                exampleEnglish: "In addition, do you know when the release period will be decided? Approximately?",
                exampleJapanese: "ちなみに、いつぐらいまでにリリースの時期が決まるか、わかりますか。",
            ),
        ]
    }
}
