import Foundation

extension Word {
    static var list1Decks: [Word] {
        [
            Word(
                id: 0,
                deckID: 1,
                japanese: "チケットを取る",
                english: "take a ticket",
                partOfSpeech: "",
                exampleEnglish: "I can't take a ticket this week because I have already taken 3.",
                exampleJapanese: "すでに3つチケットを取っているので、今週は取れません。",
            ),
            Word(
                id: 2,
                deckID: 1,
                japanese: "すでに",
                english: "already",
                partOfSpeech: "adv.",
                exampleEnglish: "The bug has already been fixed in the latest commit.",
                exampleJapanese: "そのバグはすでに最新のコミットで修正されています。",
            ),
            Word(
                id: 3,
                deckID: 1,
                japanese: "プルリクを出す",
                english: "make a pull request",
                partOfSpeech: "",
                exampleEnglish: "I made a pull request yesterday.",
                exampleJapanese: "昨日、プルリクを出しました。",
            ),
            Word(
                id: 4,
                deckID: 1,
                japanese: "開発する",
                english: "develop",
                partOfSpeech: "v.",
                exampleEnglish: "I'm developing X now.",
                exampleJapanese: "今、Xを開発しています。",
            ),
            Word(
                id: 5,
                deckID: 1,
                japanese: "修正する",
                english: "correct",
                partOfSpeech: "v.",
                exampleEnglish: "I think I'll correct it by the end of today.",
                exampleJapanese: "修正は今日中に終わると思います。",
            ),
            Word(
                id: 6,
                deckID: 1,
                japanese: "マージする",
                english: "merge",
                partOfSpeech: "v.",
                exampleEnglish: "I merged X with Y.",
                exampleJapanese: "XをYにマージしました。",
            ),
            Word(
                id: 7,
                deckID: 1,
                japanese: "進める",
                english: "move forward",
                partOfSpeech: "v. [*transitive verb 他動詞]",
                exampleEnglish: "I'm woving forward with this ticket with Ken.",
                exampleJapanese: "このチケットは、Kenさんと一緒に進めています。",
            ),
            Word(
                id: 8,
                deckID: 1,
                japanese: "[システムが]動く",
                english: "work",
                partOfSpeech: "v.",
                exampleEnglish: "I realized that the system was not working properly.",
                exampleJapanese: "システムがちゃんと動いてないことがわかった。",
            ),
            Word(
                id: 9,
                deckID: 1,
                japanese: "ちゃんと",
                english: "properly",
                partOfSpeech: "adv.",
                exampleEnglish: "The API isn’t working properly.",
                exampleJapanese: "APIが正しく動いていません。",
            ),
            Word(
                id: 10,
                deckID: 1,
                japanese: "間に合う",
                english: "be in time",
                partOfSpeech: "",
                exampleEnglish: "It seems that we'll be in time for the next week's release.",
                exampleJapanese: "来週のリリースには間に合いそうです。",
            ),
            Word(
                id: 11,
                deckID: 1,
                japanese: "状態",
                english: "status",
                partOfSpeech: "n.",
                exampleEnglish: "Is there anything ready for QA?",
                exampleJapanese: "QAしてもらえる状態のものがありますか。",
            ),
            Word(
                id: 12,
                deckID: 1,
                japanese: "課題",
                english: "issue",
                partOfSpeech: "n.",
                exampleEnglish: "We found some issues.",
                exampleJapanese: "課題が見つかった。",
            ),
            Word(
                id: 13,
                deckID: 1,
                japanese: "要件",
                english: "requirements",
                partOfSpeech: "n.",
                exampleEnglish: "I'll share requirements with TLs tomorrow.",
                exampleJapanese: "要件は明日、テックリード(TL)に共有します。",
            ),
            Word(
                id: 14,
                deckID: 1,
                japanese: "仕様",
                english: "specification document",
                partOfSpeech: "n.",
                exampleEnglish: "The specs haven't been decided yet.",
                exampleJapanese: "まだ仕様が決まってない。",
            ),
            Word(
                id: 15,
                deckID: 1,
                japanese: "固まる (*自動詞)",
                english: "take shape",
                partOfSpeech: "v. (*intransitive verb)",
                exampleEnglish: "The specs haven't taken shape yet.",
                exampleJapanese: "まだ仕様が固まっていません。",
            ),
            Word(
                id: 16,
                deckID: 1,
                japanese: "支障",
                english: "obstacle",
                partOfSpeech: "n.",
                exampleEnglish: "An obstacle interferes with it (our project).",
                exampleJapanese: "(プロジェクトに)支障が出ています。",
            ),
            Word(
                id: 17,
                deckID: 1,
                japanese: "影響",
                english: "effect",
                partOfSpeech: "n.",
                exampleEnglish: "This is not an incident that has an effect on customers.",
                exampleJapanese: "これは、お客様に影響があるインシデントじゃないです。",
            ),
            Word(
                id: 18,
                deckID: 1,
                japanese: "原因",
                english: "cause",
                partOfSpeech: "n.",
                exampleEnglish: "I will look into the causes now.",
                exampleJapanese: "これから原因を調べます。",
            ),
            Word(
                id: 19,
                deckID: 1,
                japanese: "相談する",
                english: "consult",
                partOfSpeech: "v.",
                exampleEnglish: "I'll consult with my manager.",
                exampleJapanese: "マネージャーに相談する。",
            ),
            Word(
                id: 20,
                deckID: 1,
                japanese: "困る",
                english: "be in trouble",
                partOfSpeech: "v.",
                exampleEnglish: "Do you have any difficulties?",
                exampleJapanese: "何か困ってることがありますか。",
            ),
            Word(
                id: 21,
                deckID: 1,
                japanese: "[人/チームと]連携する",
                english: "work together",
                partOfSpeech: "v.",
                exampleEnglish: "We work together with team B to do this (task).",
                exampleJapanese: "これはteam Bと連携してやっていきます。",
            ),
            Word(
                id: 22,
                deckID: 1,
                japanese: "sync(シンク)する",
                english: "sync",
                partOfSpeech: "v.",
                exampleEnglish: "I will sync with TL later.",
                exampleJapanese: "あとでテックリード(TL)とsyncしておきます。",
            ),
            Word(
                id: 23,
                deckID: 1,
                japanese: "設定する",
                english: "set",
                partOfSpeech: "v.",
                exampleEnglish: "I'll set goals / I am setting goals.",
                exampleJapanese: "目標を設定する。",
            ),
            Word(
                id: 24,
                deckID: 1,
                japanese: "反映する",
                english: "reflect",
                partOfSpeech: "v.",
                exampleEnglish: "I edited it last week, but it isn't reflected on Jira (yet).",
                exampleJapanese: "先週修正したけど、Jiraに反映されてません。",
            ),
            Word(
                id: 25,
                deckID: 1,
                japanese: "効率",
                english: "efficiency",
                partOfSpeech: "n.",
                exampleEnglish: "That method seems efficient.",
                exampleJapanese: "そのやり方は、効率がよさそう。",
            ),
            Word(
                id: 26,
                deckID: 1,
                japanese: "プルリクを出す",
                english: "create a pull request",
                partOfSpeech: "",
                exampleEnglish: "I created a pull request yesterday.",
                exampleJapanese: "昨日、プルリクを出しました。",
            ),
            Word(
                id: 27,
                deckID: 1,
                japanese: "修正する",
                english: "revise",
                partOfSpeech: "v.",
                exampleEnglish: "I think I'll revise it by the end of today.",
                exampleJapanese: "修正は今日中に終わると思います。",
            ),
            Word(
                id: 28,
                deckID: 1,
                japanese: "進める",
                english: "proceed with (something)",
                partOfSpeech: "v. [*transitive verb 他動詞]",
                exampleEnglish: "I'm proceeding with this ticket with Ken.",
                exampleJapanese: "このチケットは、Kenさんと一緒に進めています。",
            ),
            Word(
                id: 29,
                deckID: 1,
                japanese: "[システムが]動く",
                english: "operate",
                partOfSpeech: "v.",
                exampleEnglish: "I realized that the system was not operating properly.",
                exampleJapanese: "システムがちゃんと動いてないことがわかった。",
            ),
            Word(
                id: 30,
                deckID: 1,
                japanese: "間に合う",
                english: "make a deadline",
                partOfSpeech: "",
                exampleEnglish: "It seems that we'll make the release next week.",
                exampleJapanese: "来週のリリースには間に合いそうです。",
            ),
            Word(
                id: 31,
                deckID: 1,
                japanese: "支障",
                english: "hitch",
                partOfSpeech: "n.",
                exampleEnglish: "There’s a hitch in the project.",
                exampleJapanese: "プロジェクトに支障が出ています。",
            ),
            Word(
                id: 32,
                deckID: 1,
                japanese: "[人/チームと]連携する",
                english: "align with",
                partOfSpeech: "v.",
                exampleEnglish: "We are aligned with team B to do this (task).",
                exampleJapanese: "これはteam Bと連携してやっていきます。",
            ),
            Word(
                id: 33,
                deckID: 1,
                japanese: "進める",
                english: "work on",
                partOfSpeech: "v. [*transitive verb 他動詞]",
                exampleEnglish: "I'm working on this ticket with Ken.",
                exampleJapanese: "このチケットは、Kenさんと一緒に進めています。",
            ),
        ]
    }
}
